---
- name: Nginx Provisioning
  hosts: my_host
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Check Nginx
      service:
        name: nginx
        state: started
